import { Lexend } from "next/font/google"
import "./globals.css"

const UbuntuFont = Lexend({
  subsets: ['latin'],
  variable: "--font-ubu",
  weight: ["300", '400', "500", "700"],
});
export const metadata = {
  title: "Suraksha Kawach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased m-0 p-0 box-border `}>
        {children}
      </body>
    </html>
  );
}
