import "./globals.css";
import React from "react";

export const metadata = {
  title: "Suraksha Kawach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased m-0 p-0 box-border`}>
        {children}
      </body>
    </html>
  );
}
